apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "estafette-vulnerability-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "estafette-vulnerability-scanner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "estafette-vulnerability-scanner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "estafette-vulnerability-scanner.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        {{- range $key, $value := .Values.extraPodLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      annotations:
        prometheus.io/port: "9101"  
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ include "estafette-vulnerability-scanner.fullname" . }}-image-pull-secret
      {{- end }}
      serviceAccountName: {{ include "estafette-vulnerability-scanner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ template "estafette-vulnerability-scanner.imageTag" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.extraArgs }}
        args:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
          - name: "STATE_FILE_CONFIGMAP_NAME"
            value: "{{ include "estafette-vulnerability-scanner.fullname" . }}-state"
          - name: "ESTAFETTE_LOG_FORMAT"
            value: "{{ .Values.logFormat }}"
          - name: "ESTAFETTE_LOG_LEVEL"
            value: "{{ .Values.logLevel }}"
          - name: "RELEASE_NAME"
            value: "{{ .Release.Name }}"
          - name: "TRIVY_CACHE_DIR"
            value: "{{ .Values.trivyCacheDir }}"
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        ports:
          - name: metrics
            containerPort: 9101
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: state-file
          mountPath: /state
        {{- if .Values.caCerts }}
        - name: cacerts
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
        {{- end }}
        {{- if .Values.manualDbSync.enabled }}
        - name: trivy-cache
          mountPath: "{{ .Values.trivyCacheDir }}"
        {{- end }}
      {{- if .Values.manualDbSync.enabled }}
      - name: {{ .Chart.Name }}-dbsync
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.manualDbSync.image }}"
        imagePullPolicy: {{ .Values.manualDbSync.imagePullPolicy }}
        command: [ "/bin/sh", "-c", "--" ]
        args: {{ .Values.manualDbSync.script }}
        env:
          - name: "TRIVY_CACHE_DIR"
            value: "{{ .Values.trivyCacheDir }}"
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        volumeMounts:
        {{- if .Values.caCerts }}
        - name: cacerts
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
        {{- end }}
        - name: trivy-cache
          mountPath: "{{ .Values.trivyCacheDir }}"

      initContainers:
      - name: {{ .Chart.Name }}-init
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.manualDbSync.initcontainer.image }}"
        imagePullPolicy: {{ .Values.manualDbSync.initcontainer.imagePullPolicy }}
        command: [ "/bin/sh", "-c", "--" ]
        args: {{ .Values.manualDbSync.initcontainer.script }}
        env:
          - name: "TRIVY_CACHE_DIR"
            value: "{{ .Values.trivyCacheDir }}"
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        volumeMounts:
        {{- if .Values.caCerts }}
        - name: cacerts
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
        {{- end }}
        - name: trivy-cache
          mountPath: "{{ .Values.trivyCacheDir }}"

      {{- end }}
      terminationGracePeriodSeconds: 300
      volumes:
      - name: state-file
        configMap:
          name: {{ include "estafette-vulnerability-scanner.fullname" . }}-state
      {{- if .Values.caCerts }}
      - name: cacerts
        configMap:
          name: {{ include "estafette-vulnerability-scanner.fullname" . }}-cacerts
      {{- end }}
      {{- if .Values.manualDbSync.enabled }}
      - name: trivy-cache
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
