{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "estafette-vulnerability-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-vulnerability-scanner.labels" . | indent 4 }}
rules:
    - apiGroups: [""] # "" indicates the core API group
    resources:
    - configmaps
    verbs:
    - get
    - list
    - update
{{- end -}}